# Generated by Django 3.2.8 on 2021-12-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211218_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_app_profile_friends_+', to='app.Profile'),
        ),
    ]
