# Generated by Django 3.2.8 on 2021-12-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
