# Generated by Django 3.2.8 on 2021-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='profile_subs', to='app.Profile'),
        ),
    ]
